name: chainercv
channels:
- !!python/unicode
  'menpo'
- !!python/unicode
  'defaults'
dependencies:
  - cython
  - opencv3=3.2.0
  - matplotlib
  - numpy
  - scikit-learn
  - pip:
    - chainer
